//
// Created by Danelynn Ding on 7/2/22.
//

#ifndef SPA_SRC_SPA_SRC_COMPONENTS_PKB_DESIGN_EXTRACTOR_DESIGN_EXTRACTOR_H_
#define SPA_SRC_SPA_SRC_COMPONENTS_PKB_DESIGN_EXTRACTOR_DESIGN_EXTRACTOR_H_

class design_extractor {

};

#endif //SPA_SRC_SPA_SRC_COMPONENTS_PKB_DESIGN_EXTRACTOR_DESIGN_EXTRACTOR_H_
