//
// Created by Yu Heem Lai on 8/3/22.
//

#ifndef SPA_SRC_SPA_SRC_COMPONENTS_QUERY_SUBSYSTEM_PQL_EVALUATOR_SELECT_CLAUSE_H_
#define SPA_SRC_SPA_SRC_COMPONENTS_QUERY_SUBSYSTEM_PQL_EVALUATOR_SELECT_CLAUSE_H_



class select_clause {

};



#endif //SPA_SRC_SPA_SRC_COMPONENTS_QUERY_SUBSYSTEM_PQL_EVALUATOR_SELECT_CLAUSE_H_
