name: Build & Test Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team20/Code20/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --target spa

      - name: Build Unit Tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --target unit_testing

      - name: Run Unit Tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ${{runner.workspace}}/build/src/unit_testing/unit_testing

      - name: Build Integration Tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --target integration_testing

      - name: Run Integration Tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ${{runner.workspace}}/build/src/integration_testing/integration_testing

      - name: Set up Regression Tests
        shell: bash
        run: |
          mkdir -p ${{runner.workspace}}/build/regression_tests
          cp -r $GITHUB_WORKSPACE/Team20/Test20/* ${{runner.workspace}}/build/regression_tests

      - name: Run Regression Tests
        working-directory: ${{runner.workspace}}/build/regression_tests
        shell: bash
        run: python regression_tester.py

