name: Build & Test Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team20/Code20/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

  test:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 3
    strategy:
      fail-fast:true

    steps:
      - name: Run Unit Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ${{runner.workspace}}/build/src/unit_testing/unit_testing

      - name: Run Integration Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ${{runner.workspace}}/build/src/integration_testing/integration_testing

